# generate_vectors.py

PRIME_P = (1 << 255) - 19

def reduce(val):
    """True modulo — Python ints are arbitrary precision, no truncation risk."""
    return val % PRIME_P

test_cases = [
    (0,                          "Edge Case: Zero"),
    (123456789,                  "Normal Case: Value < p"),
    (PRIME_P,                    "Edge Case: Exactly p"),
    (1 << 256,                   "H1 Path: 2^256 -> 38"),
    (2 * PRIME_P,                "Edge Case: 2p -> 0"),
    (PRIME_P - 1,                "Edge Case: p-1 passthrough"),
    ((1 << 256) - 1,             "Edge Case: Max 256-bit value"),
    ((1 << 512) - 1,             "Edge Case: Max 512-bit value"),
    # Stage 2 stress: large H1 maximises H2
    ((1 << 511) - 1,             "Stage 2 Stress: Max H2"),
    # Pseudo-random
    (0xA1B2C3D4E5F67890A1B2C3D4E5F67890A1B2C3D4E5F67890A1B2C3D4E5F67890 << 256 |
     0x0987654321FEDCBA0987654321FEDCBA0987654321FEDCBA0987654321FEDCBA,
     "Normal Case: 512-bit Hash"),
]

def fmt(val, width_bits):
    """Format as fixed-width hex for SystemVerilog."""
    width_hex = width_bits // 4
    return f"{val:0{width_hex}X}"

print("`timescale 1ns / 1ps")
print("module tb_pseudo_mersenne_vectors;")
print()
print("    // ==========================================")
print("    // Auto-generated by generate_vectors.py")
print("    // Python guarantees arbitrary-precision arithmetic")
print("    // ==========================================")
print()
print("    logic [511:0] data_in;")
print("    logic [255:0] data_out;")
print()
print("    pseudo_mersenne dut (")
print("        .data_in(data_in),")
print("        .data_out(data_out)")
print("    );")
print()

# Emit localparam vectors
print(f"    localparam logic [255:0] PRIME_P = 256'h{fmt(PRIME_P, 256)};")
print()

# Emit input/expected pairs as localparams
for i, (val, name) in enumerate(test_cases):
    expected = reduce(val)
    print(f"    // {name}")
    print(f"    localparam logic [511:0] IN_{i}  = 512'h{fmt(val, 512)};")
    print(f"    localparam logic [255:0] EXP_{i} = 256'h{fmt(expected, 256)};")
    print()

# Emit test task and sequence
print("    task check(input [511:0] iv, input [255:0] ev, input string nm);")
print("        data_in = iv;")
print("        #10;")
print("        if (data_out === ev)")
print('            $display("[PASS] %s", nm);')
print("        else begin")
print('            $display("[FAIL] %s", nm);')
print('            $display("       Input:    %h", iv);')
print('            $display("       Expected: %h", ev);')
print('            $display("       Got:      %h", data_out);')
print("        end")
print("    endtask")
print()
print("    initial begin")
print('        $display("========================================");')
print('        $display("Pseudo-Mersenne Tests (Pre-computed)");')
print('        $display("========================================");')

for i, (val, name) in enumerate(test_cases):
    print(f'        check(IN_{i}, EXP_{i}, "{name}");')

print('        $display("========================================");')
print('        $display("Tests Completed");')
print('        $display("========================================");')
print("        $finish;")
print("    end")
print()
print("endmodule")